'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
import time

def comp(num):
    a = 1
    b = 1
    c = 0
    answer = 0
    
    while c < num:
        c = (a+b)                   # next sequence
        if c % 2 == 0:              
            answer = answer + c
        a = b
        b = c
    
    return(answer)

if __name__ == "__main__":
    start = time.process_time()
    print(comp(100))
    print(f"----- process time : {time.process_time() - start} seconds -----")
